//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/UiInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UiInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UiInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UiInputActions"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""21117642-1843-4638-ba59-ca3f0c5f2cef"",
            ""actions"": [
                {
                    ""name"": ""RadialChargeMeter"",
                    ""type"": ""Button"",
                    ""id"": ""5d9dc2a3-eb79-489c-9e91-fb871fda758e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""32c9400d-1f66-4611-9cee-3fbc46b77277"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RadialChargeMeter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_RadialChargeMeter = m_UI.FindAction("RadialChargeMeter", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_RadialChargeMeter;
    public struct UIActions
    {
        private @UiInputActions m_Wrapper;
        public UIActions(@UiInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @RadialChargeMeter => m_Wrapper.m_UI_RadialChargeMeter;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @RadialChargeMeter.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRadialChargeMeter;
                @RadialChargeMeter.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRadialChargeMeter;
                @RadialChargeMeter.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRadialChargeMeter;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RadialChargeMeter.started += instance.OnRadialChargeMeter;
                @RadialChargeMeter.performed += instance.OnRadialChargeMeter;
                @RadialChargeMeter.canceled += instance.OnRadialChargeMeter;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IUIActions
    {
        void OnRadialChargeMeter(InputAction.CallbackContext context);
    }
}
